// 床・持ち物に出す 道具の絵（カテゴリごとに1つ。16×16 のドット）。
//
// ゲームはこれを直接使わない。scripts/make-items.mjs がこれで public/sprites/items/<名前>.png を書き出す。
// 1文字が1ドット：'.' は透明、ほかの文字は palette の色（#rrggbb）。
// 道具は床に置かれるので、絵は下の段まで使い、左右はだいたい まん中にそろえる。

export const ICON_SIZE = 16;

export const ITEM_ART: Record<
	string,
	{ palette: Record<string, string>; rows: string[] }
> = {
	// 武器：ななめの金属バット（左下に黒いグリップ、先に黄色いスパーク＝ガッ！）
	weapon: {
		palette: {
			h: "#f4f8fc",
			s: "#c0c8d4",
			m: "#8e98a8",
			S: "#5a6272",
			// グリップの光の側（暗い床でも 持ち手が消えないように 明るめ）
			G: "#7a7e8c",
			k: "#2a2a30",
			y: "#ffe060",
			W: "#ffffff",
		},
		rows: [
			"..............y.",
			".............yWy",
			"..............y.",
			"................",
			"............hs..",
			"...........hssm.",
			"..........hssmS.",
			".........hssmS..",
			"........hssmS...",
			".......hsmS.....",
			"......hmS.......",
			".....hS.........",
			"....Gk..........",
			"...Gk...........",
			"..Gkk...........",
			"..kk............",
		],
	},
	// 板：掲示板の木の板（四隅に釘、上に小さな名札）
	shield: {
		palette: {
			e: "#5a3a1c",
			l: "#dcac72",
			f: "#c8955a",
			g: "#a87028",
			n: "#3a2418",
			c: "#f4e6c0",
		},
		rows: [
			"................",
			"................",
			"................",
			"....eeeeeeee....",
			"...elnffffnfe...",
			"...elfffffffe...",
			"...elccccccfe...",
			"...elccccccfe...",
			"...elfffffffe...",
			"...elfgffgffe...",
			"...elfgffgffe...",
			"...elfgfffffe...",
			"...elfgffgffe...",
			"...elffffgffe...",
			"...elnffffnfe...",
			"...eeeeeeeeee...",
		],
	},
	// トリップ：◆（水色の菱形）と、下にのぞく金の輪
	ring: {
		palette: {
			k: "#1c2140",
			c: "#4fd1ff",
			C: "#2a9ad0",
			w: "#ffffff",
			y: "#e0b040",
		},
		rows: [
			"................",
			"................",
			"................",
			"................",
			".......kk.......",
			"......kwck......",
			".....kwccck.....",
			".....kcccck.....",
			"....kcccccCk....",
			"....kccccCCk....",
			".....kccCCk.....",
			".....kcCCCk.....",
			"....y.kCCk.y....",
			"....y..kk..y....",
			".....y....y.....",
			"......yyyy......",
		],
	},
	// 草：www の草むら（深緑・緑・黄緑の w を3つ）と 土
	herb: {
		palette: {
			a: "#2a6a34",
			b: "#4c9a50",
			c: "#8ad08a",
			o: "#173d1f",
			d: "#6b4523",
		},
		rows: [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"......b...b.....",
			"......b...b.....",
			".a...ab.b.c...c.",
			".a...ab.b.c...c.",
			".a.a.aobobc.c.c.",
			".a.a.a.o.oc.c.c.",
			".oaoao....ococo.",
			"..o.dddddddd.o..",
		],
	},
	// スレ：クリームの紙に 赤い【 と 緑の名前欄、下に文字の線、右下を折る
	scroll: {
		palette: {
			b: "#7a5a3a",
			p: "#f5f0dc",
			r: "#d03030",
			g: "#228b22",
			t: "#3a3a3a",
			f: "#c8bc94",
		},
		rows: [
			"................",
			"................",
			"................",
			"...bbbbbbbbbbb..",
			"...bprrrpppppb..",
			"...bprrppppppb..",
			"...bprrppgggpb..",
			"...bprrppppppb..",
			"...bprrrpppppb..",
			"...bpppppppppb..",
			"...bptttttttpb..",
			"...bpppppppppb..",
			"...bpttttttppb..",
			"...bpppppppppb..",
			"...bptttttppfb..",
			"...bbbbbbbbbb...",
		],
	},
	// 杖：ななめの木の杖、先に白い AA の顔のこぶ
	staff: {
		palette: {
			l: "#c8955a",
			d: "#8a5a2a",
			o: "#4a2c14",
			w: "#ffffff",
			g: "#c8ccd8",
			k: "#1a1a1a",
		},
		rows: [
			"................",
			"................",
			"...........ooo..",
			"..........owwwo.",
			".........owkwkwo",
			".........owwwwgo",
			"..........owwgo.",
			".........ldooo..",
			"........ldo.....",
			".......ldo......",
			"......ldo.......",
			".....ldo........",
			"....ldo.........",
			"...ldo..........",
			"..ldo...........",
			".ldo............",
		],
	},
	// 矢：細い矢3本の束（鋼の矢じり、赤い ＞＞ の矢羽、まん中を結ぶ）
	arrow: {
		palette: {
			t: "#c8b090",
			m: "#dde2ea",
			r: "#e04040",
			n: "#3a2418",
		},
		rows: [
			"................",
			"................",
			"........mmm.mmm.",
			".........tm..tm.",
			"........t.m.t.m.",
			".......n...t....",
			"......t.n.t.mmm.",
			".....t...n...tm.",
			"....t...t.n.t.m.",
			"...rrrrr...n....",
			"..t...tr..t.....",
			".rrrrr.r.t......",
			"t...tr.rt.......",
			"...t.r.r........",
			"..t..rt.........",
			".....r..........",
		],
	},
	// メシ：パン（こんがりした 山型の 食パン。上に 白い つや）
	food: {
		palette: {
			k: "#3a2410",
			c: "#b86a24",
			d: "#8a4a18",
			l: "#e0a050",
			w: "#fff0c8",
			i: "#f6dca0",
		},
		rows: [
			"................",
			"................",
			"................",
			"................",
			"....kkkk.kkkk...",
			"...kllwlkcllck..",
			"..kcllwlccllcck.",
			"..kccllcccllcdk.",
			"..kcccccccccddk.",
			"...kiiiiiiiiik..",
			"...kiiiiiiiidk..",
			"...kiiiiiiiidk..",
			"...kiiiiiiiidk..",
			"...kiiiiiiiidk..",
			"...kdddddddddk..",
			"....kkkkkkkkk...",
		],
	},
	// 忍法帖の実：金の丸い実、上に赤い結び目、まん中に黒い手裏剣、右上に白いきらめき
	growth: {
		palette: {
			g: "#f0c040",
			D: "#b08020",
			h: "#fff0a8",
			r: "#e04040",
			R: "#a02828",
			k: "#1a1a1a",
			w: "#ffffff",
		},
		rows: [
			"................",
			".............w..",
			"............www.",
			".............w..",
			"......r.r.......",
			"...ghgrRrggD....",
			"..gghgDDDgggD...",
			"..ghwgggggggD...",
			"..ghggggggggD...",
			"..ggggkgkgggD...",
			"..gggggkggggD...",
			"..ggggkgkggDD...",
			"...ggggggggD....",
			"...DggggggDD....",
			"....DggggDD.....",
			".....DDDDD......",
		],
	},
};
