// 床・持ち物に出す 道具の絵（カテゴリごとに1つ。16×16 のドット）。
//
// ゲームはこれを直接使わない。scripts/make-items.mjs がこれで public/sprites/items/<名前>.png を書き出す。
// 1文字が1ドット：'.' は透明、ほかの文字は palette の色（#rrggbb）。
// 道具は床に置かれるので、絵は下の段まで使い、左右はだいたい まん中にそろえる。

export const ICON_SIZE = 16;

/** レコード（黒い 盤・溝・照り・まんなかの 穴）。label は ラベルの 色。 */
const RECORD = (
	label: string,
): { palette: Record<string, string>; rows: string[] } => ({
	palette: { k: "#16161c", g: "#3c3c48", s: "#74748a", h: "#050506", L: label },
	rows: [
		"................",
		".....kkkkkk.....",
		"...kkkggggkkk...",
		"..kkgkkkkkkgkk..",
		"..kgksskkkkkgk..",
		".kgkskkLLkkkkgk.",
		".kgkskLLLLkkkgk.",
		".kgkkLLhhLLkkgk.",
		".kgkkLLhhLLkkgk.",
		".kgkkkLLLLkkkgk.",
		".kgkkkkLLkkkkgk.",
		"..kgkkkkkkssgk..",
		"..kkgkkkkkkgkk..",
		"...kkkggggkkk...",
		".....kkkkkk.....",
		"................",
	],
});

export const ITEM_ART: Record<
	string,
	{ palette: Record<string, string>; rows: string[] }
> = {
	// 武器：ななめの金属バット（左下に黒いグリップ、先に黄色いスパーク＝ガッ！）
	weapon: {
		palette: {
			h: "#f4f8fc",
			s: "#c0c8d4",
			m: "#8e98a8",
			S: "#5a6272",
			// グリップの光の側（暗い床でも 持ち手が消えないように 明るめ）
			G: "#7a7e8c",
			k: "#2a2a30",
			y: "#ffe060",
			W: "#ffffff",
		},
		rows: [
			"..............y.",
			".............yWy",
			"..............y.",
			"................",
			"............hs..",
			"...........hssm.",
			"..........hssmS.",
			".........hssmS..",
			"........hssmS...",
			".......hsmS.....",
			"......hmS.......",
			".....hS.........",
			"....Gk..........",
			"...Gk...........",
			"..Gkk...........",
			"..kk............",
		],
	},
	// 板：掲示板の木の板（四隅に釘、上に小さな名札）
	shield: {
		palette: {
			e: "#5a3a1c",
			l: "#dcac72",
			f: "#c8955a",
			g: "#a87028",
			n: "#3a2418",
			c: "#f4e6c0",
		},
		rows: [
			"................",
			"................",
			"................",
			"....eeeeeeee....",
			"...elnffffnfe...",
			"...elfffffffe...",
			"...elccccccfe...",
			"...elccccccfe...",
			"...elfffffffe...",
			"...elfgffgffe...",
			"...elfgffgffe...",
			"...elfgfffffe...",
			"...elfgffgffe...",
			"...elffffgffe...",
			"...elnffffnfe...",
			"...eeeeeeeeee...",
		],
	},
	// トリップ：◆（水色の菱形）と、下にのぞく金の輪
	ring: {
		palette: {
			k: "#1c2140",
			c: "#4fd1ff",
			C: "#2a9ad0",
			w: "#ffffff",
			y: "#e0b040",
		},
		rows: [
			"................",
			"................",
			"................",
			"................",
			".......kk.......",
			"......kwck......",
			".....kwccck.....",
			".....kcccck.....",
			"....kcccccCk....",
			"....kccccCCk....",
			".....kccCCk.....",
			".....kcCCCk.....",
			"....y.kCCk.y....",
			"....y..kk..y....",
			".....y....y.....",
			"......yyyy......",
		],
	},
	// 草：www の草むら（深緑・緑・黄緑の w を3つ）と 土
	herb: {
		palette: {
			a: "#2a6a34",
			b: "#4c9a50",
			c: "#8ad08a",
			o: "#173d1f",
			d: "#6b4523",
		},
		rows: [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"......b...b.....",
			"......b...b.....",
			".a...ab.b.c...c.",
			".a...ab.b.c...c.",
			".a.a.aobobc.c.c.",
			".a.a.a.o.oc.c.c.",
			".oaoao....ococo.",
			"..o.dddddddd.o..",
		],
	},
	// スレ：クリームの紙に 赤い【 と 緑の名前欄、下に文字の線、右下を折る
	scroll: {
		palette: {
			b: "#7a5a3a",
			p: "#f5f0dc",
			r: "#d03030",
			g: "#228b22",
			t: "#3a3a3a",
			f: "#c8bc94",
		},
		rows: [
			"................",
			"................",
			"................",
			"...bbbbbbbbbbb..",
			"...bprrrpppppb..",
			"...bprrppppppb..",
			"...bprrppgggpb..",
			"...bprrppppppb..",
			"...bprrrpppppb..",
			"...bpppppppppb..",
			"...bptttttttpb..",
			"...bpppppppppb..",
			"...bpttttttppb..",
			"...bpppppppppb..",
			"...bptttttppfb..",
			"...bbbbbbbbbb...",
		],
	},
	// 杖：ななめの木の杖、先に白い AA の顔のこぶ
	staff: {
		palette: {
			l: "#c8955a",
			d: "#8a5a2a",
			o: "#4a2c14",
			w: "#ffffff",
			g: "#c8ccd8",
			k: "#1a1a1a",
		},
		rows: [
			"................",
			"................",
			"...........ooo..",
			"..........owwwo.",
			".........owkwkwo",
			".........owwwwgo",
			"..........owwgo.",
			".........ldooo..",
			"........ldo.....",
			".......ldo......",
			"......ldo.......",
			".....ldo........",
			"....ldo.........",
			"...ldo..........",
			"..ldo...........",
			".ldo............",
		],
	},
	// 矢：細い矢3本の束（鋼の矢じり、赤い ＞＞ の矢羽、まん中を結ぶ）
	arrow: {
		palette: {
			t: "#c8b090",
			m: "#dde2ea",
			r: "#e04040",
			n: "#3a2418",
		},
		rows: [
			"................",
			"................",
			"........mmm.mmm.",
			".........tm..tm.",
			"........t.m.t.m.",
			".......n...t....",
			"......t.n.t.mmm.",
			".....t...n...tm.",
			"....t...t.n.t.m.",
			"...rrrrr...n....",
			"..t...tr..t.....",
			".rrrrr.r.t......",
			"t...tr.rt.......",
			"...t.r.r........",
			"..t..rt.........",
			".....r..........",
		],
	},
	// メシ：パン（こんがりした 山型の 食パン。上に 白い つや）
	food: {
		palette: {
			k: "#3a2410",
			c: "#b86a24",
			d: "#8a4a18",
			l: "#e0a050",
			w: "#fff0c8",
			i: "#f6dca0",
		},
		rows: [
			"................",
			"................",
			"................",
			"................",
			"....kkkk.kkkk...",
			"...kllwlkcllck..",
			"..kcllwlccllcck.",
			"..kccllcccllcdk.",
			"..kcccccccccddk.",
			"...kiiiiiiiiik..",
			"...kiiiiiiiidk..",
			"...kiiiiiiiidk..",
			"...kiiiiiiiidk..",
			"...kiiiiiiiidk..",
			"...kdddddddddk..",
			"....kkkkkkkkk...",
		],
	},
	// 忍法帖の実：金の丸い実、上に赤い結び目、まん中に黒い手裏剣、右上に白いきらめき
	growth: {
		palette: {
			g: "#f0c040",
			D: "#b08020",
			h: "#fff0a8",
			r: "#e04040",
			R: "#a02828",
			k: "#1a1a1a",
			w: "#ffffff",
		},
		rows: [
			"................",
			".............w..",
			"............www.",
			".............w..",
			"......r.r.......",
			"...ghgrRrggD....",
			"..gghgDDDgggD...",
			"..ghwgggggggD...",
			"..ghggggggggD...",
			"..ggggkgkgggD...",
			"..gggggkggggD...",
			"..ggggkgkggDD...",
			"...ggggggggD....",
			"...DggggggDD....",
			"....DggggDD.....",
			".....DDDDD......",
		],
	},
	// お花：まどわされているときの 床の道具（ピンクの花びら・黄色い しべ・緑の茎と葉）
	flower: {
		palette: {
			h: "#ffd8ea",
			p: "#ff8fc0",
			P: "#d8508c",
			y: "#ffe870",
			Y: "#d8a020",
			g: "#6cc050",
			G: "#2f7a30",
			D: "#6a4a2a",
		},
		rows: [
			"................",
			"......hppp......",
			".....hpppPP.....",
			"..hpp.pPPP.hpp..",
			".hpppyyyyYpppP..",
			".ppppyYYYYppPPP.",
			"..pPP.PPPP.pPP..",
			".....pPPPPP.....",
			"......PPPP......",
			".......gg.......",
			"....gg.gG.......",
			"...gGGggG..gg...",
			"....GG.gGgGG....",
			".......gG.......",
			"......ggGG......",
			".....DDDDDD.....",
		],
	},

	// ───── 目的の品（持ち帰る品）。1つずつ 専用の 絵（data/items.ts の icon）
	// はじまりの原盤：金の ラベルの レコード
	genban: RECORD("#e8b830"),
	// つづきの原盤：まだ なにも 入っていない 白い ラベル
	tsuzuki: RECORD("#f0f0ea"),
	// 1001の原盤：赤い ラベル（dat落ちの 1001）
	g1001: RECORD("#d03838"),
	// 蓄音機の針：ななめの 鋼の 針と 金の 針止め
	needle: {
		palette: {
			y: "#b8862a",
			Y: "#ffe07a",
			h: "#f4f8fc",
			s: "#b4bcc8",
			m: "#6a7282",
		},
		rows: [
			"................",
			"...........yy...",
			"..........yYYy..",
			"..........yYyy..",
			"...........yy...",
			"..........hs....",
			".........hsm....",
			"........hsm.....",
			".......hsm......",
			"......hsm.......",
			".....hsm........",
			"....hsm.........",
			"...hsm..........",
			"...sm...........",
			"..m.............",
			"................",
		],
	},
	// たこのみんの たこ焼き：😡の 顔の たこ焼き（ソース・マヨ・青のり）
	takoyaki: {
		palette: {
			o: "#5a2410",
			s: "#6a2a14",
			m: "#fff4e0",
			g: "#4a9a30",
			b: "#d8683a",
			B: "#f09058",
			e: "#1a0804",
		},
		rows: [
			"................",
			"................",
			".....oooooo.....",
			"...oosmssgsoo...",
			"..osgssmsssmso..",
			"..obsssgssssbo..",
			".obbebbbbbbebbo.",
			".obbbeebbeebbbo.",
			".obbBebbbbeBbbo.",
			".obBbbbbbbbbBbo.",
			".obbbbeeeebbbbo.",
			"..obbebbbbebbo..",
			"..obbbbbbbbbbo..",
			"...oobbbbbboo...",
			".....oooooo.....",
			"................",
		],
	},
};
